{% set name = "nose2" %}
{% set version = "0.11.0" %}
{% set sha256 = "6d208d7d6ec9f9d55c74dac81c9394bc3906dbef81a8ca5420b2b9b7f8e69de9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - nose2 = nose2:discover
    - nose2-3.6 = nose2:discover

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - six >=1.7
    - coverage >=4.4.1

test:
  imports:
    - nose2
    - nose2.plugins
    - nose2.plugins.loader
    - nose2.tests
    - nose2.tests.functional
    - nose2.tests.unit
    - nose2.tools
  commands:
    - nose2 --help
    - nose2-3.6 --help

about:
  home: https://github.com/nose-devs/nose2
  summary: nose2 is the next generation of nicer testing for Python
  license: BSD
  license_family: BSD
  license_file: license.txt

extra:
  recipe-maintainers:
    - npavlovikj
